<a href="https://colab.research.google.com/github/savirhkhan/Scikit_learn_dump/blob/main/Plynomial_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [60]:
#Loading data
df = pd.read_csv('/content/drive/MyDrive/Data sets/advertising1.csv')

In [61]:
df.shape

(200, 4)

In [62]:
df.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [63]:
X = df.drop('Sales',axis =1)

In [64]:
y = df['Sales']

In [65]:
#importing polynomial features library
from sklearn.preprocessing import PolynomialFeatures

In [66]:
#creating instance of polynimial features
poly_converter = PolynomialFeatures(degree= 2,include_bias = False)

In [67]:
poly_converter.fit(X)

PolynomialFeatures(include_bias=False)

In [68]:
#transforming the features to the degree 2 without including bias means no 1
poly_features =  poly_converter.transform(X)

In [69]:
poly_features.shape

(200, 9)

In [70]:
# importing lib for train test septration on poly_features dataset created 
from sklearn.model_selection import train_test_split

In [71]:
#diving data set into train and test
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [72]:
#loading lib for linear regression 
from sklearn.linear_model import LinearRegression

In [73]:
#Creating Linear model
my_model = LinearRegression()

In [74]:
#fitting model with poly_features
my_model.fit(X_train,y_train)

LinearRegression()

In [75]:
#doing frediction on X_test data set created
test_predict = my_model.predict(X_test)

In [76]:
#Checkin Beta co-efficient
my_model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [77]:
#Importing error metrics
from sklearn.metrics import mean_absolute_error , mean_squared_error

In [78]:
#generating Mean absolute error
MAE = mean_absolute_error(y_test,test_predict)

In [79]:
#Generating Mean Squared error
MSE = mean_squared_error(y_test,test_predict)

In [80]:
#generaing Root mean squared error
RMSE = np.sqrt(MSE)

In [81]:
MSE

0.4417505510403753

In [82]:
RMSE

0.6646431757269274

In [83]:
my_model.coef_

array([ 5.17095811e-02,  1.30848864e-02,  1.20000085e-02, -1.10892474e-04,
        1.14212673e-03, -5.24100082e-05,  3.34919737e-05,  1.46380310e-04,
       -3.04715806e-05])

In [84]:
poly_features[0]

array([2.301000e+02, 3.780000e+01, 6.920000e+01, 5.294601e+04,
       8.697780e+03, 1.592292e+04, 1.428840e+03, 2.615760e+03,
       4.788640e+03])

In [85]:
X.iloc[0]

TV           230.1
Radio         37.8
Newspaper     69.2
Name: 0, dtype: float64