<a href="https://colab.research.google.com/github/savirhkhan/Scikit_learn_dump/blob/main/Plynomial_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [31]:
#Loading data
df = pd.read_csv('/content/drive/MyDrive/Data sets/advertising1.csv')

In [32]:
df.shape

(200, 5)

In [33]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [34]:
X = df.drop('Sales',axis =1)

In [35]:
y = df['Sales']

In [36]:
#importing polynomial features library
from sklearn.preprocessing import PolynomialFeatures

In [37]:
#creating instance of polynimial features
poly_converter = PolynomialFeatures(degree= 2,include_bias = False)

In [38]:
poly_converter.fit(X)

PolynomialFeatures(include_bias=False)

In [39]:
#transforming the features to the degree 2 without including bias means no 1
poly_features =  poly_converter.transform(X)

In [40]:
poly_features.shape

(200, 14)

In [41]:
# importing lib for train test septration on poly_features dataset created 
from sklearn.model_selection import train_test_split

In [42]:
#diving data set into train and test
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.3, random_state=101)

In [43]:
#loading lib for linear regression 
from sklearn.linear_model import LinearRegression

In [44]:
#Creating Linear model
my_model = LinearRegression()

In [45]:
#fitting model with poly_features
my_model.fit(X_train,y_train)

LinearRegression()

In [46]:
#doing frediction on X_test data set created
test_predict = my_model.predict(X_test)

In [47]:
#Checkin Beta co-efficient
my_model.coef_

array([-2.89169487e-03,  5.14946850e-02,  7.64689190e-03,  1.23229045e-02,
        3.21593264e-06,  4.68588745e-06,  4.79474307e-05,  9.36046004e-06,
       -1.11226738e-04,  1.13842326e-03, -5.46546234e-05,  5.13995322e-05,
        1.46150974e-04, -3.87022011e-05])

In [48]:
#Importing error metrics
from sklearn.metrics import mean_absolute_error , mean_squared_error

In [49]:
#generating Mean absolute error
MAE = mean_absolute_error(y_test,test_predict)

In [50]:
#Generating Mean Squared error
MSE = mean_squared_error(y_test,test_predict)

In [51]:
#generaing Root mean squared error
RMSE = np.sqrt(MSE)

In [52]:
MSE

0.4460379484429457

In [53]:
RMSE

0.6678607253334677

In [54]:
my_model.coef_

array([-2.89169487e-03,  5.14946850e-02,  7.64689190e-03,  1.23229045e-02,
        3.21593264e-06,  4.68588745e-06,  4.79474307e-05,  9.36046004e-06,
       -1.11226738e-04,  1.13842326e-03, -5.46546234e-05,  5.13995322e-05,
        1.46150974e-04, -3.87022011e-05])

In [55]:
poly_features[0]

array([1.000000e+00, 2.301000e+02, 3.780000e+01, 6.920000e+01,
       1.000000e+00, 2.301000e+02, 3.780000e+01, 6.920000e+01,
       5.294601e+04, 8.697780e+03, 1.592292e+04, 1.428840e+03,
       2.615760e+03, 4.788640e+03])

In [56]:
X.iloc[0]

Unnamed: 0      1.0
TV            230.1
Radio          37.8
Newspaper      69.2
Name: 0, dtype: float64